### PR TITLE
On darwin, allow process environment variables that contain a key without a value

### LINKED ISSUE #93: ProcessInfo is nil when env key is missing a value
The parser for darwin envronment variables throws an error if a key doesn't have a value due to "len(parts) != 2".  The error causes an empty types.ProcessInfo to get returned.

see https://github.com/elastic/go-sysinfo/pull/94

### PR DESCRIPTION
**Pull request by wardn**
Fixes #93.

### CODE REVIEW

**Comment by wardn** [comment]
CLA signed

**Comment by andresrc** [comment]
@elastic/agent

**Review by andrewkroh — COMMENTED** [review]
The change looks good, but I think the problem exists in other places and should be fixed at the same time. Could you please look at the other providers to see if they suffer the same issue.

I noticed the test at https://github.com/elastic/go-sysinfo/blob/master/system_test.go#L167 will need updated.

**Comment by fearful-symmetry** [comment]
@you still working on this?

**Comment by jlind23** [comment]
Bump any update there?

**Pull request merged**
