### PR TITLE
First pass at a Makefile

### PR DESCRIPTION
**Pull request by fearful-symmetry**
This is a first attempt at a basic makefile, with the goal being that `make update` should run everything that needs to be run in order for the CI to pass its initial checks.

I don't know if I've ever seen someone use file targets to install go binaries, but it seems to work.

I'd like to add a helptext and some kind of linter, but I'd like to get the basics squared away first.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
I talked about that with @andrewkroh and we both thought mage was a decent solution because of how small the makefile is and how few targets we have. Most of our docs in beats, IIRC, actually tell people to use `make fmt` and so on.

Is this an issue for windows developers?

**Comment by jsoriano** [comment]
> I talked about that with @andrewkroh and we both thought mage was a decent solution because of how small the makefile is and how few targets we have. Most of our docs in beats, IIRC, actually tell people to use `make fmt` and so on.
> 

Ok then.

> Is this an issue for windows developers?

I have found it tricky, but not sure, maybe it is my little experience developing on windows. On the other hand mage can be installed with go get.

**Comment by andrewkroh** [comment]
I would be good with either make or mage. Of course mage is more cross-platform (Windows) friendly, but there is a bit of boilerplate that needs to be added. IMHO we need to setup a separate project containing the mage boilerplate that we can reuse in all of these small projects that just want to run goimports or go-licenser for example.

**Comment by jsoriano** [comment]
> IMHO we need to setup a separate project containing the mage boilerplate that we can reuse in all of these small projects that just want to run goimports or go-licenser for example.

@andrewkroh related, but not a separated project yet https://github.com/elastic/beats/pull/13215 :slightly_smiling_face:

**Comment by fearful-symmetry** [comment]
> IMHO we need to setup a separate project containing the mage boilerplate that we can reuse in all of these small projects that just want to run goimports or go-licenser for example.

That would be a good idea, assuming it was fairly generic. The beat build tools are...incredibly heavy. Some generic make/mage roles and variables would be good, though.

**Pull request merged**
