### PR TITLE
Add crosscompiling tests

### PR DESCRIPTION
**Pull request by ruflin**
I got stuck by a crosscompile issue in https://github.com/elastic/beats/pull/5968 so I quickly put together these tests. So far this does not solve the problem but allows us to discuss on the potential solutions.

```
1 errors occurred:
--> darwin/386 error: exit status 2
Stderr: # github.com/elastic/go-sysinfo/providers/darwin
../providers/darwin/boottime_darwin.go:28:12: undefined: sysctlByName
../providers/darwin/boottime_darwin.go:32:32: tv.Sec undefined (type syscall.Timeval32 has no field or method Sec)
../providers/darwin/boottime_darwin.go:32:47: tv.Usec undefined (type syscall.Timeval32 has no field or method Usec)
../providers/darwin/memory_darwin.go:25:12: undefined: sysctlByName

make: *** [crosscompile] Error 1
```

For the above I'm not sure where `sysctlByName` by name should be defined?

@andrewkroh I also saw that you have a `.ci` folder in the repo. Would you expect `gox` to be executed from inside a go script in `.ci/scripts`?

### CODE REVIEW

**Comment by ruflin** [comment]
It seems all the issue are related to 32bit darwin builds. Based on our support matrix we only support 10.12 (https://www.elastic.co/support/matrix). As far as I could find all mac hardware that supports 10.12 is already 64bit. Golang has still support for darwin 32bit as the minimal requirement is 10.8 and it seems there some machines could still be 32bit.

Should we remove crosscompiling for 32bit here and in beats?

**Comment by tsg** [comment]
@ruflin we only package and offer for download mac 64 bits, so I don't see any issues in removing the cross compilation for 32 bits.

**Comment by andrewkroh** [comment]
In Beats I explicitly filter all architectures except amd64 for darwin because AFAIK no one uses darwin on those archictures. 

`./libbeat/scripts/Makefile:58:GOX_OSARCH?=!darwin/arm !darwin/arm64 !darwin/386 ## @building Space separated list of GOOS/GOARCH pairs to build by "make crosscompile".`

In go-sysinfo I should have architecture specific build tags guarding this code since it only works on amd64.

**Comment by ruflin** [comment]
Rebased on top of https://github.com/elastic/go-sysinfo/pull/4

**Comment by ruflin** [comment]
@andrewkroh Stumbled over this one when reviewing PRs. Worth merging as is or are there changes needed?

**Comment by ruflin** [comment]
@andrewkroh Thoughts on what we should do with this one?

**Comment by ruflin** [comment]
Closing as I didn't make any progress.

**Pull request closed without merging**
